//fix = physics_fixture_create();
//physics_fixture_set_box_shape(fix,sprite_width*image_xscale,sprite_height*image_yscale);
//physics_fixture_set_awake(fix,true);
//physics_fixture_set_density(fix,1);
//physics_fixture_set_restitution(fix,0);
//physics_fixture_set_collision_group(fix,1);
//physics_fixture_set_linear_damping(fix,4);
//physics_fixture_set_angular_damping(fix,4);
//physics_fixture_set_friction(fix,100);
//physics_fixture_bind_ext(fix,self,0,0);
//physics_fixture_delete(fix);